# This workflow is submit to first test result

name: Pre-action CI

on:
  workflow_run:
    workflows: ["First Node.js CI"]
    types:
      - completed

jobs:
  pred:
    # The rest of this workflow will be abord if First Node.js CI failed
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile
        run: echo Code compiled